FROM postgres

LABEL org.opencontainers.image.source https://github.com/ruchira088/video-downloader-back-end

RUN apt update && \
    apt install python3-pip zip -y && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install awscli