FROM postgres

ENV GIT_BRANCH {{ git_branch }}
ENV GIT_COMMIT {{ git_commit }}
ENV BUILD_TIMESTAMP {{ build_timestamp }}

RUN apt update && \
    apt install python3-pip zip -y && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install awscli

ADD ./run-db-backup.sh /opt/

CMD [ "/opt/run-db-backup.sh" ]