FROM openjdk:11-jre-slim

RUN apt-get update && \
    apt-get upgrade -y

WORKDIR /opt/video-downloader

ADD target/universal/video-downloader-*.tgz .

CMD [ "/opt/video-downloader/bin/video-downloader" ]
