apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: "{{ k8s_namespace }}"
spec:
  serviceName: postgres-service
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      branch: "{{ git_branch }}"
  template:
    metadata:
      labels:
        app: postgres
        branch: "{{ git_branch }}"
    spec:
      containers:
        - name: postgres-container
          image: postgres:17
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              memory: 1Gi
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          envFrom:
            - configMapRef:
                name: postgres-config-map
            - secretRef:
                name: postgres-secrets
          ports:
            - name: postgres-port
              containerPort: 5432
          readinessProbe:
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            exec:
              command:
                - sh
                - -c
                - pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"
          livenessProbe:
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
            exec:
              command:
                - sh
                - -c
                - pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"
          startupProbe:
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 24
            exec:
              command:
                - sh
                - -c
                - pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path
        resources:
          requests:
            storage: 10Gi
