apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: forward-proxy-ingress
  namespace: "{{ k8s_namespace }}"
spec:
  tls:
    - secretName: forward-proxy-tls-secret
      hosts:
        - "{{ forward_proxy_hostname }}"
  rules:
    - host: "{{ forward_proxy_hostname }}"
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: forward-proxy-service
                port:
                  name: tiny-proxy-port