apiVersion: v1
kind: Secret
metadata:
  name: forward-proxy-secrets
  namespace: "{{ k8s_namespace }}"
type: Opaque
stringData:
{% for key, value in forward_proxy.secrets.items() %}
  "{{ key }}": "{{ value }}"
{% endfor %}