version = 0.1

[default.global.parameters]
stack_name = "fallback-api"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
stack_name = "fallback-api"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=dev"
resolve_s3 = true

[default.local_start_api.parameters]
port = 8000
