apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: "{{ k8s_namespace }}"
spec:
  selector:
    app: redis
    branch: "{{ git_branch }}"
  ports:
    - name: redis-port
      port: 6379
      targetPort: 6379
