apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: "{{ k8s_namespace }}"
spec:
  serviceName: redis-service
  replicas: 1
  selector:
    matchLabels:
      app: redis
      branch: "{{ git_branch }}"
  template:
    metadata:
      labels:
        app: redis
        branch: "{{ git_branch }}"
    spec:
      containers:
        - name: redis-container
          image: redis:8
          command:
            - sh
            - -c
            - redis-server --requirepass "$REDIS_PASSWORD" --appendonly yes
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 512Mi
          envFrom:
            - secretRef:
                name: redis-secrets
          ports:
            - name: redis-port
              containerPort: 6379
          readinessProbe:
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            exec:
              command:
                - sh
                - -c
                - redis-cli -a "$REDIS_PASSWORD" ping
          livenessProbe:
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
            exec:
              command:
                - sh
                - -c
                - redis-cli -a "$REDIS_PASSWORD" ping
          volumeMounts:
            - mountPath: /data
              name: redis-data
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path
        resources:
          requests:
            storage: 1Gi
