FROM eclipse-temurin:25-jre

LABEL org.opencontainers.image.source=https://github.com/ruchira088/video-downloader-back-end

ENV GIT_BRANCH {{ git_branch }}
ENV GIT_COMMIT {{ git_commit }}
ENV BUILD_TIMESTAMP {{ build_timestamp }}

WORKDIR /opt/video-downloader-{{ app_name }}

ADD video-downloader-{{ app_name }}-*.tgz .

CMD [ "/opt/video-downloader-{{ app_name }}/bin/video-downloader-{{ app_name }}" ]