FROM ghcr.io/ruchira088/video-downloader-db-operations-base:version-2025-05-24

LABEL org.opencontainers.image.source=https://github.com/ruchira088/video-downloader-back-end

ENV GIT_BRANCH {{ git_branch }}
ENV GIT_COMMIT {{ git_commit }}
ENV BUILD_TIMESTAMP {{ build_timestamp }}

ADD ./run-db-restore.sh /opt/

CMD [ "/opt/run-db-restore.sh" ]